// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class AchievementsData : IData
{
    public int ID => achievements_id;

    public int achievements_id;
    public string Grade;
    public int Counts;
    public bool Achieved;
    public int Condition;
    public string Desc;
    public int MissionType;
    public string Desc_Ko;
    public int TargetID;
}

[Serializable]
public class AchievementsDataTable
{
    public List<AchievementsData> achievementsdata;
}
