// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class CollectionData : IData
{
    public int ID => Item_id;

    public int Item_id;
    public string Name;
    public int MaxStack;
    public int ZeroInt;
    public float ZeroFloat;
    public string SampleString;
    public string Desc;
    public bool SampleBool;
}

[Serializable]
public class CollectionDataTable
{
    public List<CollectionData> collectiondata;
}
