// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class EnemyData : IData
{
    public int ID => Enemy_Id;

    public int Enemy_Id;
    public bool isBoss;
    public string Enemy_Name;
    public int Max_Hp;
    public float Patrol_Speed;
    public float Chase_Speed;
    public float Detect_Range;
    public float Disdetect_Range;
    public float Approch_Range;
    public int[] Skill_Set;
    public int[] Exskill_Set;
    public string Enemy_path;
}

[Serializable]
public class EnemyDataTable
{
    public List<EnemyData> enemydata;
}
