// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class EnemySkillData : IData
{
    public int ID => Skill_id;

    public int Skill_id;
    public string Skill_name;
    public int Damage;
    public int Damage2;
    public int Damage3;
    public int HealAmount;
    public float Cooldown;
    public float Range;
    public float TriggerHP;
    public string Desc;
}

[Serializable]
public class EnemySkillDataTable
{
    public List<EnemySkillData> enemyskilldata;
}
