// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SampleSingleData
{
    public int SampleInt;
    public float SampleFloat;
    public int ZeroInt;
    public float ZeroFloat;
    public string SampleString;
    public string ZeroString;
    public bool SampleBool;
    public int[] IntArray;
    public string[] StringArray;
    public float[] FloatArray;
    public bool[] BoolArray;
}
