// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SkillData : IData
{
    public int ID => Skill_id;

    public int Skill_id;
    public string P_Skill_Name;
    public int[] Damages;
    public int BuffValue;
    public int Stamina;
    public float Cooldown;
    public float Duration;
    public string Desc;
}

[Serializable]
public class SkillDataTable
{
    public List<SkillData> skilldata;
}
