// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SoulData : IData
{
    public int ID => Item_id;

    public int Item_id;
    public string Name;
    public int MaxStack;
    public string Desc;
}

[Serializable]
public class SoulDataTable
{
    public List<SoulData> souldata;
}
