// Auto-generated by GoogleSheetsToJsonConverter
using System;
using System.Collections.Generic;

[Serializable]
public class SoundData : IData
{
    public int ID => Sound_id;

    public int Sound_id;
    public string Sound_name;
    public bool Loop;
    public string Desc;
    public string Sound_path;
    public float Volume;
    public float Pitch;
}

[Serializable]
public class SoundDataTable
{
    public List<SoundData> sounddata;
}
